name: scaling_cpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - cpuonly
  - faiss-cpu=1.8.0
  
  - pip:
    - omegaconf
    - hydra-core
    - tqdm
    - transformers
    - sentence_transformers
    - pyserini
    - datasketch
